### ISSUE TITLE
Hang when closing a specific repository window.

### ISSUE THREAD

**Issue by jmatta1** [SublimeTextIssues/Merge#28] opened 2018-09-26 14:50 UTC
Sublime Merge hangs when it closes the window for a specific repository. It also hangs when trying to switch repositories from that repository to another, since that repository is what it is opening when it starts this is particularly troublesome.

System Information:
macOS High Sierra Version 10.13.6
MacBook Pro (Retina, 15-inch. Mid 2015)
Processor 2.8Ghz Intel Core i7
Memory 16 GB 1600MHz DDR3
Graphics Intel Iris Pro 1536MB

Sublime Merge Information:
Version 1058 and Version 1061

When I tried to close a somewhat large repository (called Rune), Sublime Merge hung and refused to close. After some time, I used force quit and that resulted in the first error report (err_rep1.txt). I then reopened sublime merge, opened another repository and then tried to close the Rune repository. Sublime merge again hung and had to be force quit (err_rep2.txt). I then opened Sublime Merge, checked for updates, updated to build 1061, opened another repository and attempted to close the Rune repository, again it hung and I had to force quit it (err_rep3.txt). Finally I tried using switch repository to switch from Rune to another repository. Again Sublime Merge hung and had to be force quit (err_rep4.txt). A bit more testing shows it has no problem closing the window of the second repository, only when closing the window holding the Rune repository.

Unfortunately, since Sublime Merge is opening the Rune repository whenever it opens, I need to change the path to the repository that makes Sublime Merge hang so that the Sublime Merge does not open it on start.

[err_rep1.txt](https://github.com/SublimeTextIssues/Merge/files/2420162/err_rep1.txt)
[err_rep2.txt](https://github.com/SublimeTextIssues/Merge/files/2420163/err_rep2.txt)
[err_rep3.txt](https://github.com/SublimeTextIssues/Merge/files/2420164/err_rep3.txt)
[err_rep4.txt](https://github.com/SublimeTextIssues/Merge/files/2420165/err_rep4.txt)

**Comment by jmatta1** [comment] 2018-09-26 22:59
A brief test showed that this still occurs in Build 1062

**Comment by jskinner** [comment] 2018-09-27 19:50
Thanks for the details, the reports give a good indication of what the problem is.

A proper fix should be out next week, but in the mean time, you can delete the file `~/Library/Application Support/Sublime Merge/Local/Session.sublime_session`, to stop Sublime Merge from reopening the last repositories on startup.

**Comment by jmatta1** [comment] 2018-09-27 21:30
Thanks! I will do that in the future (I just renamed the directory from "Rune" to "Rune_Repo", loaded a different repo and then changed it back to "Rune".

**Comment by jskinner** [comment] 2018-09-28 10:33
I believe this should be fixed in dev build 1063 at https://www.sublimemerge.com/dev, please let me know if it's not

**Comment by jmatta1** [comment] 2018-09-28 12:24
That seems to have fixed it! I can switch to and from the troublesome repository and close that repository window when needed. Which of those fixes was it? The prevent window creation off screen?

**Comment by jskinner** [comment] 2018-09-28 12:43
Great to hear. The fix wasn't mentioned in the changelog, just in case it wasn't the actual root cause. The logic that orders commits in the commit graph needs to calculate reachability, and it wasn't implemented correctly, such that the right sort of commit topology would result in it looping almost forever.

**Comment by jmatta1** [comment] 2018-09-28 17:15
That makes sense given the some of the hairy commit history in Rune. Should I close those this, or will you do that when it is in the non-dev release?

**Closed as completed** 2018-09-29 14:58 UTC
Labels: T: bug, C: git, R: fixed
